resolver: lts-11.0

packages:
  - ff
  - ff-core
  - ff-qt

extra-deps:
  # ff:
    - crdt-9.3
  # ff:test:
    - git: https://github.com/cblp/crdt.git
      commit: v9.3
      subdirs:
        - crdt-test
  # ff-qt:
    # - qtah-cpp-qt5-0.4.0
    # - qtah-generator-0.4.0
    # - qtah-qt5-0.4.0
    - git: https://gitlab.com/cblp/qtah.git
      commit: '728d330'  # 0.4.0 + cblp 2018-03-07
      subdirs:
        - qtah
        - qtah-cpp
        - qtah-generator
  # qtah:
    - hoppy-generator-0.4.0
    - hoppy-runtime-0.4.0
    - hoppy-std-0.4.0
