resolver: lts-11.0

packages:
  - ff
  - ff-core
  - ff-qt

extra-deps:
  # ff:
    - crdt-9.3
  # ff:test:
    - git: https://github.com/cblp/crdt.git
      commit: v9.3
      subdirs:
        - crdt-test
